name: Demo Workflow
on: push
jobs:
  mt_test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: '21'
      - name: Build with Gradle
        run: ./app/gradlew build